MineralAirways/Models/Vuelos.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MineralAirways.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vuelos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vuelos()
        {
            this.ReservasVuelos = new HashSet<ReservasVuelos>();
            this.Tramos = new HashSet<Tramos>();
        }
    
        public int VueloID { get; set; }
        public int OrigenID { get; set; }
        public int DestinoID { get; set; }
        public System.DateTime FechaHoraSalida { get; set; }
        public int NumeroVuelo { get; set; }
        public int AvionID { get; set; }
        public bool Visible { get; set; }
    
        public virtual Aviones Aviones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReservasVuelos> ReservasVuelos { get; set; }
        public virtual Rutas Rutas { get; set; }
        public virtual Rutas Rutas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tramos> Tramos { get; set; }
    }
}

MineralAirways/Controllers/VuelosController.cs
using MineralAirways.Models;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace MineralAirways.Controllers
{
    public class VuelosController : BaseController
    {
        private DAPEntities db = new DAPEntities();

        // GET: Vuelos
        public ActionResult Index()
        {
            var vuelos = db.Vuelos.Include(v => v.Aviones).Include(v => v.Rutas).Include(v => v.Rutas1).Where(x => x.Visible);
            return View(vuelos.ToList());
        }

        public ActionResult fechasdatapicker()
        {
            var vuelos = db.Vuelos.Include(v => v.Aviones).Include(v => v.Rutas).Include(v => v.Rutas1);
            return View(vuelos.ToList());
        }

        // GET: Vuelos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vuelos vuelos = db.Vuelos.Find(id);
            if (vuelos == null)
            {
                return HttpNotFound();
            }
            return View(vuelos);
        }

        // GET: Vuelos/Create
        public ActionResult Create()
        {
            ViewBag.AvionID = new SelectList(db.Aviones, "AvionID", "MatriculaDelAvion");
            ViewBag.DestinoID = new SelectList(db.Rutas.Where(x => x.Visible), "RutaID", "Codigo");
            ViewBag.OrigenID = new SelectList(db.Rutas.Where(x => x.Visible), "RutaID", "Codigo");
            return View();
        }

        // POST: Vuelos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "VueloID,OrigenID,DestinoID,FechaHoraSalida,NumeroVuelo,AvionID")] Vuelos vuelos)
        {
            if (ModelState.IsValid)
            {
                vuelos.Visible = true;
                db.Vuelos.Add(vuelos);
                db.SaveChanges();

                var vueloBd = db.Vuelos.OrderByDescending(x => x.VueloID).FirstOrDefault();
                if (vueloBd != null) {
                    var tramoMaxId = db.Tramos.Any() ? db.Tramos.Max(x => x.TramoID) : 0;
                    var tramo = new Tramos
                    {
                        VueloID = vueloBd.VueloID,
                        DestinoID = vueloBd.DestinoID,
                        FechaHoraSalida = vueloBd.FechaHoraSalida,
                        OrigenID = vueloBd.OrigenID,
                        TramoID = tramoMaxId + 1
                    };

                    db.Tramos.Add(tramo);
                    db.SaveChanges();
                }

                return RedirectToAction("Index");
            }

            ViewBag.AvionID = new SelectList(db.Aviones, "AvionID", "MatriculaDelAvion", vuelos.AvionID);
            ViewBag.DestinoID = new SelectList(db.Rutas, "RutaID", "Ciudad", vuelos.DestinoID);
            ViewBag.OrigenID = new SelectList(db.Rutas, "RutaID", "Ciudad", vuelos.OrigenID);
            return View(vuelos);
        }

        // GET: Vuelos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vuelos vuelos = db.Vuelos.Find(id);
            if (vuelos == null)
            {
                return HttpNotFound();
            }
            ViewBag.AvionID = new SelectList(db.Aviones, "AvionID", "MatriculaDelAvion", vuelos.AvionID);
            ViewBag.DestinoID = new SelectList(db.Rutas, "RutaID", "Ciudad", vuelos.DestinoID);
            ViewBag.OrigenID = new SelectList(db.Rutas, "RutaID", "Ciudad", vuelos.OrigenID);
            return View(vuelos);
        }

        // POST: Vuelos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "VueloID,OrigenID,DestinoID,FechaHoraSalida,NumeroVuelo,AvionID,Visible")] Vuelos vuelos)
        {
            if (ModelState.IsValid)
            {
                db.Entry(vuelos).State = EntityState.Modified;
                db.SaveChanges();

                var vueloBd = db.Vuelos.FirstOrDefault(x => x.VueloID == vuelos.VueloID);
                if (vueloBd != null) {
                    var tramoBd = db.Tramos.FirstOrDefault(x => x.VueloID == vueloBd.VueloID
                    && x.OrigenID == vueloBd.OrigenID && x.DestinoID == vueloBd.DestinoID);

                    if (tramoBd != null) {
                        tramoBd.DestinoID = vueloBd.DestinoID;
                        tramoBd.OrigenID = vueloBd.OrigenID;
                        tramoBd.FechaHoraSalida = vueloBd.FechaHoraSalida;
                        db.SaveChanges();
                    }

                }

                return RedirectToAction("Index");
            }
            ViewBag.AvionID = new SelectList(db.Aviones, "AvionID", "MatriculaDelAvion", vuelos.AvionID);
            ViewBag.DestinoID = new SelectList(db.Rutas, "RutaID", "Ciudad", vuelos.DestinoID);
            ViewBag.OrigenID = new SelectList(db.Rutas, "RutaID", "Ciudad", vuelos.OrigenID);
            return View(vuelos);
        }

        // GET: Vuelos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vuelos vuelos = db.Vuelos.Find(id);
            if (vuelos == null)
            {
                return HttpNotFound();
            }
            return View(vuelos);
        }

        // POST: Vuelos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Vuelos vuelos = db.Vuelos.Find(id);
            vuelos.Visible = false;
            //db.Vuelos.Remove(vuelos);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MineralAirways/Views/Vuelos/Create.cshtml
@model MineralAirways.Models.Vuelos

@{
    ViewBag.Title = "Crear Vuelo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <h1 class="text-primary col-md-9">Crear Vuelo</h1>
    <div class="form-inline col-md-3">
        <br />
        <a href="@Url.Action("Index","Vuelos")" class="btn btn-primary pull-right btn-sm"><span class="glyphicon glyphicon-chevron-left"></span>&nbsp;Volver</a>
    </div>
</div>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">        
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.OrigenID, "Origen", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("OrigenID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.OrigenID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DestinoID, "Destino", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DestinoID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DestinoID, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.FechaHoraSalida, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaHoraSalida, new { htmlAttributes = new { @class = "form-control"} })
                
                @Html.ValidationMessageFor(model => model.FechaHoraSalida, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumeroVuelo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumeroVuelo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumeroVuelo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AvionID, "Matrícula del Avion", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AvionID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AvionID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<script>
    $('#FechaHoraSalida').datetimepicker({
        format: 'DD-MM-YYYY HH:mm:ss',
        locale: 'es',
        widgetPositioning: {
            horizontal: 'auto',
            vertical: 'bottom'
        }
    });
    $(document).ready(function () {
        $('#FechaHoraSalida').attr("class", "form-control datefield");
    });
</script>

MineralAirways/Views/Vuelos/Delete.cshtml
@model MineralAirways.Models.Vuelos

@{
    ViewBag.Title = "Eliminar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <h1 class="text-primary col-md-9">Eliminar Vuelo</h1>
    <div class="form-inline col-md-3">
        <br />
        <a href="@Url.Action("Index","Vuelos")" class="btn btn-primary pull-right btn-sm"><span class="glyphicon glyphicon-chevron-left"></span>&nbsp;Volver</a>
    </div>
</div>

<h3>¿Estás seguro que deseas eliminar este vuelo?</h3>
<div>    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FechaHoraSalida)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaHoraSalida)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumeroVuelo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumeroVuelo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Aviones.MatriculaDelAvion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Aviones.MatriculaDelAvion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rutas.Ciudad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rutas.Ciudad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rutas1.Ciudad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rutas1.Ciudad)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-default" /> 
            @*@Html.ActionLink("Back to List", "Index")*@
        </div>
    }
</div>

MineralAirways/Views/Vuelos/Details.cshtml
@model MineralAirways.Models.Vuelos

@{
    ViewBag.Title = "Detalle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <h1 class="text-primary col-md-9">Detalle del Vuelo</h1>
    <br />
    <div class="form-inline col-md-2">
        <a href="@Url.Action("Edit","Vuelos", new { id = Model.VueloID})" class="btn btn-primary pull-right btn-sm"><span class="glyphicon glyphicon-edit"></span>&nbsp;Editar Vuelo</a>
    </div>
    <div class="form-inline col-md-1">        
        <a href="@Url.Action("Index","Vuelos")" class="btn btn-primary pull-right btn-sm"><span class="glyphicon glyphicon-chevron-left"></span>&nbsp;Volver</a>
    </div>
</div>

<div>   
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FechaHoraSalida)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaHoraSalida)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumeroVuelo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumeroVuelo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Aviones.MatriculaDelAvion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Aviones.MatriculaDelAvion)
        </dd>

        <dt>
            Origen
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rutas1.Ciudad)
        </dd>

        <dt>
            Destino
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rutas.Ciudad)
        </dd>

    </dl>
</div>
@*<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.VueloID }) |
    @Html.ActionLink("Back to List", "Index")
</p>*@

MineralAirways/Views/Vuelos/Edit.cshtml
@model MineralAirways.Models.Vuelos

@{
    ViewBag.Title = "Editar Vuelo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">      
    <h1 class="text-primary col-md-9">Editar Vuelo</h1>
    <div class="form-inline col-md-3">
        <br />        
        <a href="@Url.Action("Index","Vuelos")" class="btn btn-primary pull-right btn-sm"><span class="glyphicon glyphicon-chevron-left"></span>&nbsp;Volver</a>
    </div>    
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">       
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.VueloID)
        @Html.HiddenFor(model => model.Visible)

        <div class="form-group">
            @Html.LabelFor(model => model.OrigenID, "Origen", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("OrigenID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.OrigenID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DestinoID, "Destino", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DestinoID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DestinoID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaHoraSalida, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaHoraSalida, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaHoraSalida, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumeroVuelo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumeroVuelo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumeroVuelo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AvionID, "Matrícula del Avión", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AvionID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AvionID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<script>
    $('#FechaHoraSalida').datetimepicker({
        format: 'DD-MM-YYYY HH:mm:ss',
        locale: 'es',
        widgetPositioning: {
            horizontal: 'auto',
            vertical: 'bottom'
        }
    });
    $(document).ready(function () {
        $('#FechaHoraSalida').attr("class", "form-control datefield");
    });
</script>

MineralAirways/Views/Vuelos/Index.cshtml
@model IEnumerable<MineralAirways.Models.Vuelos>

@{
    ViewBag.Title = "Vuelos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br />
<div class="row">
    <div class="form-inline col-md-12">
        <a class="btn btn-primary pull-right btn-sm" href="@Url.Action("Create", "Vuelos")">
            <span class="glyphicon glyphicon-plus"></span>
            Crear Vuelo
        </a>
    </div>
</div>
<br />
<div class="row">
    <table class="table table-hover tablaMantenedores">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.FechaHoraSalida)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.NumeroVuelo)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Aviones.MatriculaDelAvion)
                </th>
                <th>
                    Origen
                </th>
                <th>
                    Destino
                </th>
                <th></th>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.FechaHoraSalida)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.NumeroVuelo)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Aviones.MatriculaDelAvion)
                </th>
                <th>
                    Origen
                </th>
                <th>
                    Destino
                </th>
                <th></th>
            </tr>
        </tfoot>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.FechaHoraSalida)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NumeroVuelo)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Aviones.MatriculaDelAvion)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Rutas1.Codigo)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Rutas.Codigo)
                    </td>
                    <td>
                        @Html.ActionLink(" ", "Edit", new { id = item.VueloID }, new { @class = "glyphicon glyphicon-edit", title = "Editar" }) |
                        @Html.ActionLink(" ", "Details", new { id = item.VueloID }, new { @class = "glyphicon glyphicon-search", title = "Detalles" }) |
                        @Html.ActionLink(" ", "Delete", new { id = item.VueloID }, new { @class = "glyphicon glyphicon-remove", title = "Eliminar" })
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<script src="~/Scripts/Tabla/ConfigTable.js"></script>

MineralAirways/Views/Vuelos/fechasdatapicker.cshtml
@model IEnumerable<MineralAirways.Models.Vuelos>

@{
    ViewBag.Title = "fechasdatapicker";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>fechasdatapicker</h2>

<section class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4" id="datepicker"></div>
    @*<div class="col-md-4">*@
    @*<button id="BuscarBtn" type="button" class="btn btn-primary btn-sm">Buscar</button>*@
    @*</div>*@
</section>
<br />
<div id="SearchResults">
</div>


<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    @*<tr>
        <th>
            @Html.DisplayNameFor(model => model.FechaHoraSalida)
        </th>
        
        <th></th>
    </tr>*@

@foreach (var item in Model) {
    <tr>
        <td>
           @item.FechaHoraSalida.Day
               
        </td>
        <td>
            @item.OrigenID
        </td>
        <td>
            @item.DestinoID
        </td>       
       
    </tr>
}

</table>


<script>
 $.datepicker.regional['es'] = {
 closeText: 'Cerrar',
 prevText: '< Ant',
 nextText: 'Sig >',
 currentText: 'Hoy',
 monthNames: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
 monthNamesShort: ['Ene','Feb','Mar','Abr', 'May','Jun','Jul','Ago','Sep', 'Oct','Nov','Dic'],
 dayNames: ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'],
 dayNamesShort: ['Dom','Lun','Mar','Mié','Juv','Vie','Sáb'],
 dayNamesMin: ['Do','Lu','Ma','Mi','Ju','Vi','Sá'],
 weekHeader: 'Sm',
 dateFormat: 'dd/mm/yy',
 firstDay: 1,
 isRTL: false,
 showMonthAfterYear: false,
 yearSuffix: '',
 orientation: 'top left',
 minDate: "+0D",
 maxDate: "+2M, -5D"
 };
 $.datepicker.setDefaults($.datepicker.regional['es']);
</script>

@*<script>
     $("#datepicker").datepicker({
         onSelect: function (date) {
             var origen = $("#Origen").val();
                    var destino = $("#Destino").val();
                    var fecha = $("#datepicker").val();

                    if (origen == '') {
                        BootstrapDialog.alert({
                            title: '¡Validación!',
                            message: '<strong>El Origen es requerido.</strong>',
                            type: BootstrapDialog.TYPE_WARNING,
                        });
                    }
                    else if (destino == '') {
                        BootstrapDialog.alert({
                            title: '¡Validación!',
                            message: '<strong>El Destino es requerido.</strong>',
                            type: BootstrapDialog.TYPE_WARNING,
                        });
                    }
                    else {
                        var url = '@Url.Action("BusquedaVistaParcialReservaVuelo", "HomeLogin")?origen=' + origen + '&destino=' + destino + '&fecha=' + fecha;
                        $('#SearchResults').load(url);
                        setTimeout(function () {
                            if ($('.container-fluid').html() != '') {
                                $("#loading-modal").hide();
                            }
                        }, 10000);
                    }
             }
         });
</script>*@
<script>

 function noExcursion(date){
     var day = date.getDay();
     //var day;

// aqui indicamos el numero correspondiente a los dias que ha de bloquearse (el 0 es Domingo, 1 Lunes, etc...)
return [(day != 0 && day != 2 && day != 3 && day != 5 && day != 6), ''];
};

//Crear el datepicker
$("#datepicker").datepicker({
beforeShowDay: noExcursion,

    //$('#datepicker').datepicker({
    //    onSelect: function (dateText, inst) {
    //        alert(dateText);

    //   }

});
</script>