MineralAirways/Models/Tramos.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MineralAirways.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tramos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tramos()
        {
            this.ReservasVuelos = new HashSet<ReservasVuelos>();
        }
    
        public int TramoID { get; set; }
        public int VueloID { get; set; }
        public int OrigenID { get; set; }
        public int DestinoID { get; set; }
        public System.DateTime FechaHoraSalida { get; set; }
        public bool Visible { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReservasVuelos> ReservasVuelos { get; set; }
        public virtual Rutas Rutas { get; set; }
        public virtual Rutas Rutas1 { get; set; }
        public virtual Vuelos Vuelos { get; set; }
    }
}

MineralAirways/Controllers/TramosController.cs
using MineralAirways.Models;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace MineralAirways.Controllers
{
    public class TramosController : BaseController
    {
        private DAPEntities db = new DAPEntities();

        // GET: Tramos
        public ActionResult Index()
        {
            var tramos = db.Tramos.Include(t => t.Rutas).Include(t => t.Rutas1).Include(t => t.Vuelos);
            return View(tramos.ToList());
        }

        // GET: Tramos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tramos tramos = db.Tramos.Find(id);
            if (tramos == null)
            {
                return HttpNotFound();
            }
            return View(tramos);
        }

        // GET: Tramos/Create
        public ActionResult Create()
        {
            ViewBag.DestinoID = new SelectList(db.Rutas, "RutaID", "Ciudad");
            ViewBag.OrigenID = new SelectList(db.Rutas, "RutaID", "Ciudad");
            ViewBag.VueloID = new SelectList(db.Vuelos, "VueloID", "VueloID");
            return View();
        }

        // POST: Tramos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TramoID,VueloID,OrigenID,DestinoID,FechaHoraSalida")] Tramos tramos)
        {
            if (ModelState.IsValid)
            {
                db.Tramos.Add(tramos);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.DestinoID = new SelectList(db.Rutas, "RutaID", "Ciudad", tramos.DestinoID);
            ViewBag.OrigenID = new SelectList(db.Rutas, "RutaID", "Ciudad", tramos.OrigenID);
            ViewBag.VueloID = new SelectList(db.Vuelos, "VueloID", "VueloID", tramos.VueloID);
            return View(tramos);
        }

        // GET: Tramos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tramos tramos = db.Tramos.Find(id);
            if (tramos == null)
            {
                return HttpNotFound();
            }
            ViewBag.DestinoID = new SelectList(db.Rutas, "RutaID", "Ciudad", tramos.DestinoID);
            ViewBag.OrigenID = new SelectList(db.Rutas, "RutaID", "Ciudad", tramos.OrigenID);
            ViewBag.VueloID = new SelectList(db.Vuelos, "VueloID", "VueloID", tramos.VueloID);
            return View(tramos);
        }

        // POST: Tramos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TramoID,VueloID,OrigenID,DestinoID,FechaHoraSalida")] Tramos tramos)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tramos).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DestinoID = new SelectList(db.Rutas, "RutaID", "Ciudad", tramos.DestinoID);
            ViewBag.OrigenID = new SelectList(db.Rutas, "RutaID", "Ciudad", tramos.OrigenID);
            ViewBag.VueloID = new SelectList(db.Vuelos, "VueloID", "VueloID", tramos.VueloID);
            return View(tramos);
        }

        // GET: Tramos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tramos tramos = db.Tramos.Find(id);
            if (tramos == null)
            {
                return HttpNotFound();
            }
            return View(tramos);
        }

        // POST: Tramos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tramos tramos = db.Tramos.Find(id);
            db.Tramos.Remove(tramos);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MineralAirways/Views/Tramos/Create.cshtml
@model MineralAirways.Models.Tramos

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <h1 class="text-primary col-md-9">Crear Escala</h1>
    <div class="form-inline col-md-3">
        <br />
        <a href="@Url.Action("Index","Tramos")" class="btn btn-primary pull-right btn-sm"><span class="glyphicon glyphicon-chevron-left"></span>&nbsp;Volver</a>
    </div>
</div>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.VueloID, "VueloID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("VueloID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.VueloID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OrigenID, "OrigenID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("OrigenID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.OrigenID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DestinoID, "DestinoID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DestinoID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DestinoID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaHoraSalida, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaHoraSalida, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaHoraSalida, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<script>
    $('#FechaHoraSalida').datetimepicker({
        format: 'DD-MM-YYYY hh:mm:ss',
        locale: 'es',
        widgetPositioning: {
            horizontal: 'auto',
            vertical: 'bottom'
        }
    });
    $(document).ready(function () {
        $('#FechaHoraSalida').attr("class", "form-control datefield");
    });
</script>

MineralAirways/Views/Tramos/Delete.cshtml
@model MineralAirways.Models.Tramos

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <h1 class="text-primary col-md-9">Eliminar Escala</h1>
    <div class="form-inline col-md-3">
        <br />
        <a href="@Url.Action("Index","Tramos")" class="btn btn-primary pull-right btn-sm"><span class="glyphicon glyphicon-chevron-left"></span>&nbsp;Volver</a>
    </div>
</div>

<h3>¿Estás seguro que deseas eliminar esta escala?</h3>
<div>    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FechaHoraSalida)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaHoraSalida)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rutas.Ciudad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rutas.Ciudad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rutas1.Ciudad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rutas1.Ciudad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Vuelos.VueloID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Vuelos.VueloID)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-default" />         
        </div>
    }
</div>

MineralAirways/Views/Tramos/Details.cshtml
@model MineralAirways.Models.Tramos

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <h1 class="text-primary col-md-9">Detalle de la Escala</h1>
    <br />
    <div class="form-inline col-md-2">
        <a href="@Url.Action("Edit","Tramos", new { id = Model.TramoID})" class="btn btn-primary pull-right btn-sm"><span class="glyphicon glyphicon-edit"></span>&nbsp;Editar Escala</a>
    </div>
    <div class="form-inline col-md-1">
        <a href="@Url.Action("Index","Tramos")" class="btn btn-primary pull-right btn-sm"><span class="glyphicon glyphicon-chevron-left"></span>&nbsp;Volver</a>
    </div>
</div>
<div>    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FechaHoraSalida)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaHoraSalida)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rutas.Ciudad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rutas.Ciudad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rutas1.Ciudad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rutas1.Ciudad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Vuelos.VueloID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Vuelos.VueloID)
        </dd>

    </dl>
</div>

MineralAirways/Views/Tramos/Edit.cshtml
@model MineralAirways.Models.Tramos

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <h1 class="text-primary col-md-9">Editar Escala</h1>
    <div class="form-inline col-md-3">
        <br />
        <a href="@Url.Action("Index","Tramos")" class="btn btn-primary pull-right btn-sm"><span class="glyphicon glyphicon-chevron-left"></span>&nbsp;Volver</a>
    </div>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.TramoID)

        <div class="form-group">
            @Html.LabelFor(model => model.VueloID, "VueloID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("VueloID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.VueloID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OrigenID, "OrigenID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("OrigenID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.OrigenID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DestinoID, "DestinoID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DestinoID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DestinoID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaHoraSalida, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaHoraSalida, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaHoraSalida, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<script>
    $('#FechaHoraSalida').datetimepicker({
        format: 'DD-MM-YYYY hh:mm:ss',
        locale: 'es',
        widgetPositioning: {
            horizontal: 'auto',
            vertical: 'bottom'
        }
    });
    $(document).ready(function () {
        $('#FechaHoraSalida').attr("class", "form-control datefield");
    });
</script>

MineralAirways/Views/Tramos/Index.cshtml
@model IEnumerable<MineralAirways.Models.Tramos>

@{
    ViewBag.Title = "Escalas";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<div class="row">
    <div class="form-inline col-md-12">
        <a class="btn btn-primary pull-right btn-sm" href="@Url.Action("Create", "Tramos")">
            <span class="glyphicon glyphicon-plus"></span>
            Crear Escala
        </a>
    </div>
</div>
<br />
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Vuelos.NumeroVuelo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaHoraSalida)
        </th>
        <th>
           Origen
        </th>
        <th>
            Destino
        </th>        
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Vuelos.NumeroVuelo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FechaHoraSalida)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Rutas1.Ciudad)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Rutas.Ciudad)
        </td>
        
        <td>
            @Html.ActionLink(" ", "Edit", new { id = item.TramoID }, new { @class = "glyphicon glyphicon-edit", title = "Editar" }) |
            @Html.ActionLink(" ", "Details", new { id = item.TramoID }, new { @class = "glyphicon glyphicon-search", title = "Detalles" }) |
            @Html.ActionLink(" ", "Delete", new { id = item.TramoID }, new { @class = "glyphicon glyphicon-remove", title = "Eliminar" })
        </td>
    </tr>
}

</table>