MineralAirways/Models/ReservasVuelos.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MineralAirways.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservasVuelos
    {
        public int ReservaVueloID { get; set; }
        public int AvionID { get; set; }
        public int TramoID { get; set; }
        public Nullable<int> PasajeroID { get; set; }
        public Nullable<bool> ConfirmacionAsiento { get; set; }
        public Nullable<System.DateTime> FechaHoraConfirmación { get; set; }
        public Nullable<System.DateTime> FechaHoraCancelacion { get; set; }
        public int VueloID { get; set; }
        public int AsientoID { get; set; }
    
        public virtual Asientos Asientos { get; set; }
        public virtual Aviones Aviones { get; set; }
        public virtual Pasajeros Pasajeros { get; set; }
        public virtual Tramos Tramos { get; set; }
        public virtual Vuelos Vuelos { get; set; }
    }
}

MineralAirways/Controllers/ReservasVuelosController.cs
using ClosedXML.Excel;
using MineralAirways.Models;
using System;
using System.Data;
using System.Data.Entity;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace MineralAirways.Controllers
{
    public class ReservasVuelosController : BaseController
    {
        private DAPEntities db = new DAPEntities();

        // GET: ReservasVuelos

        //public ActionResult Manifiesto(string sortOrder, string currentFilter, string searchString, int? page)
        //{
        //    ViewBag.CurrentSort = sortOrder;
        //    ViewBag.NumVueloSortParm = String.IsNullOrEmpty(sortOrder) ? "numvuelo_desc" : "";
        //    //ViewBag.FechaHoraSalidaSortParm = sortOrder == "Date" ? "fechahorasalida_desc" : "Date";
        //    ViewBag.RutSortParm = String.IsNullOrEmpty(sortOrder) ? "rut_desc" : "";
        //    ViewBag.AsientoSortParm = String.IsNullOrEmpty(sortOrder) ? "asiento_desc" : "";
            
        //    if (searchString != null)
        //    {
        //        page = 1;
        //    }
        //    else
        //    {
        //        searchString = currentFilter;
        //    }

        //    ViewBag.CurrentFilter = searchString;
        //    var reservasVuelos = from s in db.ReservasVuelos.Include(r => r.Asientos).Include(r => r.Aviones).Include(r => r.Pasajeros).Include(r => r.Vuelos).Include(r=> r.Tramos)
        //                         select s;
        //    //if (!String.IsNullOrEmpty(searchString))
        //    //{
        //    //    reservasVuelos = reservasVuelos.Where(s=>s.Vuelos.NumeroVuelo.)||
        //    //}
        //    switch (sortOrder)
        //    {
        //        case "numvuelo_desc":
        //            reservasVuelos = reservasVuelos.OrderByDescending(s => s.Vuelos.NumeroVuelo);
        //            break;
        //        //case "fechahorasalida_desc":
        //        //    reservasVuelos = reservasVuelos.OrderByDescending(s => s.Vuelos.FechaHoraSalida);
        //        //    break;
        //        case "rut_desc":
        //            reservasVuelos = reservasVuelos.OrderByDescending(s => s.Pasajeros.Rut);
        //            break;
        //        case "asiento_desc":
        //            reservasVuelos = reservasVuelos.OrderByDescending(s => s.Asientos.Descripcion);
        //            break;
        //        //case "cargo_desc":
        //        //    pasajeros = pasajeros.OrderByDescending(s => s.Cargo);
        //        //    break;
        //        //case "mail_desc":
        //        //    pasajeros = pasajeros.OrderByDescending(s => s.EMail);
        //        //    break;
        //        //case "asiento_desc":
        //        //    pasajeros = pasajeros.OrderByDescending(s => s.AsientoAsignado);
        //        //    break;
        //        //default:  // Name ascending 
        //        //    pasajeros = pasajeros.OrderBy(s => s.Rut);
        //        //    break;
        //    }
        //    int pageSize = 10;
        //    int pageNumber = (page ?? 1);
        //    return View(reservasVuelos.ToPagedList(pageNumber, pageSize));
        //}
        public ActionResult Index(string sortOrder)
        {
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.RutSortParm = String.IsNullOrEmpty(sortOrder) ? "rut_desc" : "";
            ViewBag.NumVueloSortParm = String.IsNullOrEmpty(sortOrder) ? "numvuelo_desc" : "";
            ViewBag.AsientoSortParm = String.IsNullOrEmpty(sortOrder) ? "asiento_desc" : "";
            ViewBag.SalidaVueloSortParm = sortOrder == "FechaSalida" ? "fechasalidavuelo_desc" : "FechaSalida";
            ViewBag.ConfirmacionVueloSortParm = sortOrder == "FechaConfirmacion" ? "fechaconfirmacionvuelo_desc" : "FechaConfirmacion";
            ViewBag.CancelacionVueloSortParm = sortOrder == "FechaCancelacion" ? "fechacancelacionvuelo_desc" : "FechaCancelacion";
            var reservasvuelos = from s in db.ReservasVuelos.Include(r => r.Asientos).Include(r => r.Aviones).Include(r => r.Pasajeros).Include(r => r.Vuelos)
                                 select s;
            
            switch (sortOrder)
            {
                case "name_desc":
                    reservasvuelos = reservasvuelos.OrderByDescending(s => s.Pasajeros.Nombres);
                    break;
                case "rut_desc":
                    reservasvuelos = reservasvuelos.OrderByDescending(s => s.Pasajeros.Rut);
                    break;
                case "asiento_desc":
                    reservasvuelos = reservasvuelos.OrderBy(s => s.Asientos.AsientoID);
                    break;
                case "numvuelo_desc":
                    reservasvuelos = reservasvuelos.OrderByDescending(s => s.Vuelos.NumeroVuelo);
                    break;
                case "FechaSalida":
                    reservasvuelos = reservasvuelos.OrderBy(s => s.Vuelos.FechaHoraSalida);
                    break;
                case "fechasalidavuelo_desc":
                    reservasvuelos = reservasvuelos.OrderByDescending(s => s.Vuelos.FechaHoraSalida);
                    break;
                case "fechaConfirmacion":
                    reservasvuelos = reservasvuelos.OrderBy(s => s.FechaHoraConfirmación);
                    break;
                case "fechaconfirmacionvuelo_desc":
                    reservasvuelos = reservasvuelos.OrderByDescending(s => s.FechaHoraConfirmación);
                    break;
                case "fechaCancelacion":
                    reservasvuelos = reservasvuelos.OrderBy(s => s.FechaHoraCancelacion);
                    break;
                case "fechacancelacionvuelo_desc":
                    reservasvuelos = reservasvuelos.OrderByDescending(s => s.FechaHoraCancelacion);
                    break;
                default:
                    reservasvuelos = reservasvuelos.OrderBy(s => s.Pasajeros.Nombres);
                    break;
            }
            //var reservasVuelos = db.ReservasVuelos.Include(r => r.Asientos).Include(r => r.Aviones).Include(r => r.Pasajeros).Include(r => r.Vuelos);
            return View(reservasvuelos.ToList());            
        }

        // GET: ReservasVuelos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ReservasVuelos reservasVuelos = db.ReservasVuelos.Find(id);
            if (reservasVuelos == null)
            {
                return HttpNotFound();
            }
            return View(reservasVuelos);
        }

        // GET: ReservasVuelos/Create
        public ActionResult Create()
        {
            ViewBag.AsientoID = new SelectList(db.Asientos, "AsientoID", "Descripcion");
            ViewBag.AvionID = new SelectList(db.Aviones, "AvionID", "MatriculaDelAvion");
            ViewBag.PasajeroID = new SelectList(db.Pasajeros, "PasajeroID", "Rut");
            ViewBag.VueloID = new SelectList(db.Vuelos, "VueloID", "NumeroVuelo");            
            return View();
        }

        // POST: ReservasVuelos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ReservaVueloID,TramoID,AvionID,PasajeroID,ConfirmacionAsiento,FechaHoraConfirmación,FechaHoraCancelacion,VueloID,AsientoID")] ReservasVuelos reservasVuelos)
        {
            if (ModelState.IsValid)
            {
                db.ReservasVuelos.Add(reservasVuelos);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.AsientoID = new SelectList(db.Asientos, "AsientoID", "Descripcion", reservasVuelos.AsientoID);
            ViewBag.AvionID = new SelectList(db.Aviones, "AvionID", "MatriculaDelAvion", reservasVuelos.AvionID);
            ViewBag.PasajeroID = new SelectList(db.Pasajeros, "PasajeroID", "Rut", reservasVuelos.PasajeroID);
            ViewBag.VueloID = new SelectList(db.Vuelos, "VueloID", "NumeroVuelo", reservasVuelos.VueloID);            
            return View(reservasVuelos);
        }

        // GET: ReservasVuelos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ReservasVuelos reservasVuelos = db.ReservasVuelos.Find(id);
            if (reservasVuelos == null)
            {
                return HttpNotFound();
            }
            ViewBag.AsientoID = new SelectList(db.Asientos, "AsientoID", "ColumnaAsiento", reservasVuelos.AsientoID);
            ViewBag.AvionID = new SelectList(db.Aviones, "AvionID", "MatriculaDelAvion", reservasVuelos.AvionID);
            ViewBag.PasajeroID = new SelectList(db.Pasajeros, "PasajeroID", "Rut", reservasVuelos.PasajeroID);
            ViewBag.VueloID = new SelectList(db.Vuelos, "VueloID", "VueloID", reservasVuelos.VueloID);            
            return View(reservasVuelos);
        }

        // POST: ReservasVuelos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ReservaVueloID,TramoID,AvionID,PasajeroID,ConfirmacionAsiento,FechaHoraConfirmación,FechaHoraCancelacion,VueloID,AsientoID")] ReservasVuelos reservasVuelos)
        {
            if (ModelState.IsValid)
            {
                db.Entry(reservasVuelos).State = EntityState.Modified;
                db.SaveChanges();

MineralAirways/Views/ReservasVuelos/Create.cshtml
@model MineralAirways.Models.ReservasVuelos

@{
    ViewBag.Title = "ReservaVuelos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <h1 class="text-primary col-md-9">Crear Reserva de Vuelos</h1>
    <div class="form-inline col-md-3">
        <br />
        <a href="@Url.Action("Index","ReservasVuelos")" class="btn btn-primary pull-right btn-sm"><span class="glyphicon glyphicon-chevron-left"></span>&nbsp;Volver</a>
    </div>
</div>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
        
    <div class="form-horizontal">        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
               
        <div class="form-group">
            @Html.LabelFor(model => model.AvionID, "AvionID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AvionID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AvionID, "", new { @class = "text-danger" })
            </div>
        </div>
    
        <div class="form-group">
            @Html.LabelFor(model => model.PasajeroID, "PasajeroID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PasajeroID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PasajeroID, "", new { @class = "text-danger" })
            </div>
        </div>
    
        <div class="form-group">
            @Html.LabelFor(model => model.ConfirmacionAsiento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.ConfirmacionAsiento)
                    @Html.ValidationMessageFor(model => model.ConfirmacionAsiento, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
    
        <div class="form-group">
            @Html.LabelFor(model => model.FechaHoraConfirmación, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaHoraConfirmación, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaHoraConfirmación, "", new { @class = "text-danger" })
            </div>
        </div>
    
        <div class="form-group">
            @Html.LabelFor(model => model.FechaHoraCancelacion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaHoraCancelacion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaHoraCancelacion, "", new { @class = "text-danger" })
            </div>
        </div>
    
        <div class="form-group">
            @Html.LabelFor(model => model.VueloID, "VueloID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("VueloID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.VueloID, "", new { @class = "text-danger" })
            </div>
        </div>
    
        <div class="form-group">
            @Html.LabelFor(model => model.AsientoID, "AsientoID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AsientoID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AsientoID, "", new { @class = "text-danger" })
            </div>
        </div>
    
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<script>
    $('#FechaHoraConfirmaci_n,#FechaHoraCancelacion').datetimepicker({
        format: 'DD-MM-YYYY HH:mm:ss',
        locale: 'es',
        widgetPositioning: {
            horizontal: 'auto',
            vertical: 'bottom'
        }
    });
    $(document).ready(function () {
        $('#FechaHoraConfirmaci_n,#FechaHoraCancelacion').attr("class", "form-control datefield");
        $('#ConfirmacionAsiento').attr("class", "form-control list-box tri-state");
    });
</script>

MineralAirways/Views/ReservasVuelos/Delete.cshtml
@model MineralAirways.Models.ReservasVuelos

@{
    ViewBag.Title = "Eliminar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <h1 class="text-primary col-md-9">Eliminar Reserva Vuelo</h1>
    <div class="form-inline col-md-3">
        <br />
        <a href="@Url.Action("Index","ReservasVuelos")" class="btn btn-primary pull-right btn-sm"><span class="glyphicon glyphicon-chevron-left"></span>&nbsp;Volver</a>
    </div>
</div>

<h3>¿Estás seguro que deseas eliminar esta reserva de vuelo?</h3>
<div>    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ConfirmacionAsiento)
        </dt>
    
        <dd>
            @Html.DisplayFor(model => model.ConfirmacionAsiento)
        </dd>
    
        <dt>
            @Html.DisplayNameFor(model => model.FechaHoraConfirmación)
        </dt>
    
        <dd>
            @Html.DisplayFor(model => model.FechaHoraConfirmación)
        </dd>
    
        <dt>
            @Html.DisplayNameFor(model => model.FechaHoraCancelacion)
        </dt>
    
        <dd>
            @Html.DisplayFor(model => model.FechaHoraCancelacion)
        </dd>
    
        <dt>
            @Html.DisplayNameFor(model => model.Asientos.ColumnaAsiento)
        </dt>
    
        <dd>
            @Html.DisplayFor(model => model.Asientos.ColumnaAsiento)
        </dd>
    
        <dt>
            @Html.DisplayNameFor(model => model.Aviones.MatriculaDelAvion)
        </dt>
    
        <dd>
            @Html.DisplayFor(model => model.Aviones.MatriculaDelAvion)
        </dd>
    
        <dt>
            @Html.DisplayNameFor(model => model.Pasajeros.Rut)
        </dt>
    
        <dd>
            @Html.DisplayFor(model => model.Pasajeros.Rut)
        </dd>
    
        <dt>
            @Html.DisplayNameFor(model => model.Vuelos.VueloID)
        </dt>
    
        <dd>
            @Html.DisplayFor(model => model.Vuelos.VueloID)
        </dd>    
    
    </dl>
    
    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()
    
        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-default" />          
        </div>
    }
</div>

MineralAirways/Views/ReservasVuelos/DescargarPlanilla.cshtml
@model MineralAirways.Models.ReservaVueloFiltroPlanillaVm
@{
    ViewBag.Title = "Descargar Planilla Reservas de Vuelo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form id="form-exportar-excel">
    <div class="row">
        <h1 class="text-primary col-md-9">Descargar Planilla Manifiesto</h1>
        <div class="form-inline col-md-3">
            <br />
            <a id="btnDescargar" class="btn btn-primary pull-right btn-sm" data-loading-text="Descargando espere por favor...">
                <span class="glyphicon glyphicon-download"></span>
                Descargar
            </a>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="form-horizontal">
            <div class="form-group">
                @Html.LabelFor(model => model.NumeroVuelo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NumeroVuelo, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.FechaHoraSalida, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FechaHoraSalida, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>

            <div class="form-group col-md-2">
                <a id="btnLimpiar" class="btn btn-primary pull-left btn-sm">
                    <span class="glyphicon glyphicon-remove-circle"></span>
                    Limpiar
                </a>
            </div>
                       
            <div class="form-group col-md-10">                
            </div>
        </div>        
    </div>
</form>



<script>
    $('#FechaHoraSalida').datetimepicker({
        format: 'DD-MM-YYYY HH:mm',
        locale: 'es',
        widgetPositioning: {
            horizontal: 'auto',
            vertical: 'bottom'
        }
    });

    $(document).ready(function () {
        $('#FechaHoraSalida').attr("class", "form-control datefield");

        $("#btnDescargar").off('click').click(function () {
            var $btn = $("#btnDescargar");
            $btn.button('loading');
            $("input").focus(function () {
                $btn.button('reset');
            });

            var vuelo = $("#NumeroVuelo").val();
            var fecha = $("#FechaHoraSalida").val();

            monitorDescargaExcel();
            window.location = '@Url.Action("ExportarExcel", "ReservasVuelos")?numeroVuelo=' + vuelo + '&fechaSalida=' + fecha + '&processToken=' + @ViewBag.processToken;            
        });

        $("#btnLimpiar").off('click').click(function () {
            $("#NumeroVuelo").val('');
            $("#FechaHoraSalida").val('');
        });
    });
</script>
<script>
    function monitorDescargaExcel() {
        $("#loading-modal").show();
        var interval = setInterval(function () {
            var cookieValue = $.cookie('processToken');
            if (cookieValue == '@ViewBag.processToken') {
                $("#loading-modal").hide();
                var $btn = $("#btnDescargar");
                $btn.button('reset');
                clearInterval(interval);
                $.removeCookie('processToken', { path: '/' });
            }
        }, 1000);
    }
</script>

MineralAirways/Views/ReservasVuelos/DescargarPlanillaCancelado.cshtml
@model MineralAirways.Models.ReservaVueloFiltroPlanillaVm
@{
    ViewBag.Title = "Descargar Manifiesto de Cancelados";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form id="form-exportar-excel">
    <div class="row">
        <h1 class="text-primary col-md-9">Descargar Planilla Manifiesto Cancelados</h1>
        <div class="form-inline col-md-3">
            <br />
            <a id="btnDescargar" class="btn btn-primary pull-right btn-sm" data-loading-text="Descargando espere por favor...">
                <span class="glyphicon glyphicon-download"></span>
                Descargar
            </a>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="form-horizontal">
            <div class="form-group">
                @Html.LabelFor(model => model.NumeroVuelo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NumeroVuelo, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.FechaHoraInicio, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FechaHoraInicio, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.FechaHoraFin, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FechaHoraFin, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>

            <div class="form-group col-md-2">
                <a id="btnLimpiar" class="btn btn-primary pull-left btn-sm">
                    <span class="glyphicon glyphicon-remove-circle"></span>
                    Limpiar
                </a>
            </div>

            <div class="form-group col-md-10">
            </div>
        </div>
    </div>
</form>
<script>
    $('#FechaHoraInicio,#FechaHoraFin').datetimepicker({
        format: 'DD-MM-YYYY HH:mm',
        locale: 'es',
        widgetPositioning: {
            horizontal: 'auto',
            vertical: 'bottom'
        }
    });

    $(document).ready(function () {
        $('#FechaHoraInicio,#FechaHoraFin').attr("class", "form-control datefield");

        $("#btnDescargar").off('click').click(function () {
            var $btn = $("#btnDescargar");
            $btn.button('loading');
            
            var vuelo = $("#NumeroVuelo").val();
            var fechaInicio = $("#FechaHoraInicio").val();
            var fechaFin = $("#FechaHoraFin").val();

            if (vuelo == '0' || vuelo == '') {
                BootstrapDialog.alert({
                    title: '¡Validación!',
                    message: '<strong>Ingresar número de vuelo.</strong>',
                    type: BootstrapDialog.TYPE_WARNING,
                });
                $btn.button('reset');
                return;
            }
            else if (fechaInicio == '')
            {
                BootstrapDialog.alert({
                    title: '¡Validación!',
                    message: '<strong>Ingresar fecha de inicio.</strong>',
                    type: BootstrapDialog.TYPE_WARNING,
                });
                $btn.button('reset');
                return;
            }
            else if (fechaFin == '') {
                BootstrapDialog.alert({
                    title: '¡Validación!',
                    message: '<strong>Ingresar fecha de fin.</strong>',
                    type: BootstrapDialog.TYPE_WARNING,
                });
                $btn.button('reset');
                return;
            }
            else if (fechaFin < fechaInicio) {
                BootstrapDialog.alert({
                    title: '¡Validación!',
                    message: '<strong>Fecha fin debe ser mayor o igual a la fecha inicio de vuelos.</strong>',
                    type: BootstrapDialog.TYPE_WARNING,
                });
                $btn.button('reset');
                return;
            }

            monitorDescargaExcel();
            window.location = '@Url.Action("ExportarExcelCancelado", "ReservasVuelos")?numeroVuelo=' + vuelo + '&fechaInicio=' + fechaInicio + '&fechaFin=' + fechaFin + '&processToken=' + @ViewBag.processToken;            
        });

        $("#btnLimpiar").off('click').click(function () {
            $("#NumeroVuelo").val('');
            $('#FechaHoraInicio,#FechaHoraFin').val('');
        });        
    });
</script>
<script>
    function monitorDescargaExcel() {
        $("#loading-modal").show();
        var interval = setInterval(function () {
            var cookieValue = $.cookie('processToken');            
            if (cookieValue == '@ViewBag.processToken') {
                $("#loading-modal").hide();
                var $btn = $("#btnDescargar");
                $btn.button('reset');                
                clearInterval(interval);
                $.removeCookie('processToken', { path: '/' });
            }
        }, 1000);
    }
</script>

MineralAirways/Views/ReservasVuelos/Details.cshtml
@model MineralAirways.Models.ReservasVuelos

@{
    ViewBag.Title = "Detalle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <h1 class="text-primary col-md-9">Detalle de la Reserva del Vuelo</h1>
    <br />
    <div class="form-inline col-md-2">
        <a href="@Url.Action("Edit","ReservasVuelos", new { id = Model.ReservaVueloID})" class="btn btn-primary pull-right btn-sm"><span class="glyphicon glyphicon-edit"></span>&nbsp;Editar Reserva Vuelo</a>
    </div>
    <div class="form-inline col-md-1">
        <a href="@Url.Action("Index","ReservasVuelos")" class="btn btn-primary pull-right btn-sm"><span class="glyphicon glyphicon-chevron-left"></span>&nbsp;Volver</a>
    </div>
</div>

<div class="row">    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ConfirmacionAsiento)
        </dt>
    
        <dd>
            @Html.DisplayFor(model => model.ConfirmacionAsiento)
        </dd>
    
        <dt>
            @Html.DisplayNameFor(model => model.FechaHoraConfirmación)
        </dt>
    
        <dd>
            @Html.DisplayFor(model => model.FechaHoraConfirmación)
        </dd>
    
        <dt>
            @Html.DisplayNameFor(model => model.FechaHoraCancelacion)
        </dt>
    
        <dd>
            @Html.DisplayFor(model => model.FechaHoraCancelacion)
        </dd>
    
        <dt>
            @Html.DisplayNameFor(model => model.Asientos.ColumnaAsiento)
        </dt>
    
        <dd>
            @Html.DisplayFor(model => model.Asientos.ColumnaAsiento)
        </dd>
    
        <dt>
            @Html.DisplayNameFor(model => model.Aviones.MatriculaDelAvion)
        </dt>
    
        <dd>
            @Html.DisplayFor(model => model.Aviones.MatriculaDelAvion)
        </dd>
    
        <dt>
            @Html.DisplayNameFor(model => model.Pasajeros.Rut)
        </dt>
    
        <dd>
            @Html.DisplayFor(model => model.Pasajeros.Rut)
        </dd>
    
        <dt>
            @Html.DisplayNameFor(model => model.Vuelos.VueloID)
        </dt>
    
        <dd>
            @Html.DisplayFor(model => model.Vuelos.VueloID)
        </dd>   
    </dl>
</div>   